### ISSUE TITLE
New release tag

### ISSUE THREAD

**Issue by mattn** [go-gota/gota#100]
v0.9.0 does not include fix of broken import.

https://github.com/go-gota/gota/commit/7d8acfb8259f6135fb372d0966d9b6a23161c430#diff-80cec47501f12ea2f50aa0ff5c6bca95

Could you please tag newer?

**Comment by mattn** [comment]
@kniren please

**Comment by kniren** [comment]
Done!

**Comment by kniren** [comment]
After running `go test` I found a couple of issues, so I released an immediate version hotfix `v0.10.1`.

**Comment by mattn** [comment]
Thank you!
