### ISSUE TITLE
Support for ReadHTML

### ISSUE THREAD

**Issue by typeless** [go-gota/gota#105]
It would be useful to add `ReadHTML` support.

I am not sure if we should make it into the `dataframe` package, which will introduce the `golang/x/net/html` dependency.
A possibility is to add an `importer` package for it alongside the existing `dataframe` and `series`.

**Comment by kniren** [comment]
I'm OK with including this dependency if we get good value out of it :)

**Comment by kniren** [comment]
Merged on dev branch
