### ISSUE TITLE
\src\gonum.org\v1\gonum\lapack\gonum\lapack.go:39:15: syntax error: unexpected p, expecting semicolon or newline or )

### ISSUE THREAD

**Issue by iamapickle** [go-gota/gota#120]
on go doing 
 go get github.com/go-gota/gota/dataframe
im getting the above mentioned error
in the line 
    dlamchE = 0x1p-53

**Comment by julienrbrt** [comment]
I personally could not reproduce. Do you still have that issue?

**Comment by kniren** [comment]
Can't reproduce either. It was probably fixed upstream in gonum. Closing the issue.
