### ISSUE TITLE
[Question] Does it support int64 type

### ISSUE THREAD

**Issue by pradithya** [go-gota/gota#142]
As the title suggest, does it support int64? From the documentation it does support `int` type, but how will it handle `int64` series?
Thanks for the awesome project!

**Comment by chrmang** [comment]
Hi Pradithya,
it supports int64 on 64Bit Machines. There is no special int64 code inside the project - only generic int. 
As stated in https://tour.golang.org/basics/11 
> The int, uint, and uintptr types are usually 32 bits wide on 32-bit systems and 64 bits wide on 64-bit systems.
To answer your question: It depends .....
Have Fun
