### ISSUE TITLE
GOPATH will be removed, are we planning to migrate to use module

### ISSUE THREAD

**Issue by Prithvipal** [go-gota/gota#143]
As part of the Go1.16 release note, it is mentioned that Go1.17 will drop the support for GOPATH. 
Are we planning to migrate this repository to use Go Modules?

Here is the official statement:
```
We plan to drop support for GOPATH mode in Go 1.17. In other words, Go 1.17 will ignore GO111MODULE. If you have projects that do not build in module-aware mode, now is the time to migrate. 
```

Link for more detail: https://blog.golang.org/go116-module-changes

**Comment by chrmang** [comment]
With version v0.11.0 we support Go modules.

**Comment by yoonghm** [comment]
Hi, I am not sure if this is related. I am using go 1.17. I tried 
`go install github.com/go-gota/gota` but it gives

```
go install: github.com/go-gota/gota@latest: module github.com/go-gota/gota@latest found (v0.11.0), but does not contain package github.com/go-gota/gota
```

Thanks for your work.
