### ISSUE TITLE
not finding groupby function, was it added 

### ISSUE THREAD

**Issue by jahed-proj** [go-gota/gota#145]
Hello ,

Issue #13 refers to groupby and split. Not sure if the function was added. I am not finding the functions. Could you please help me with a  groupby function. I just need to group on specific columns.

**Comment by chrmang** [comment]
Hi,

thank you for your interest on gota. There was a pull request for this issue: https://github.com/go-gota/gota/pull/24 Unfortunately, this PR was not merged and this issue remains open.

**Comment by chrmang** [comment]
Hi,

thanks to @wanglong001 , we have now groupby in `dev` branch.
