### ISSUE TITLE
Problem installing on windows 10 x64 go 16

### ISSUE THREAD

**Issue by jcbritobr** [go-gota/gota#158]
I'm trying to install dataframes with go 16.6 on windows 10 x64 and got the following message. After that the go.mod file is not updated:

```
go get: github.com/kniren/gota@v0.10.1 updating to
        github.com/kniren/gota@v0.11.0: parsing go.mod:     
        module declares its path as: github.com/go-gota/gota
                but was required as: github.com/kniren/gota
```

**Comment by chrmang** [comment]
Hi,

it seems your command was `go get github.com/kniren/gota`. This points to an outdated version of gota. Please try `go get github.com/go-gota/gota`.
For further questions, you can also use our [Slack channel](https://gophers.slack.com/archives/C026APJUHA6).

Have Fun

**Comment by jcbritobr** [comment]
> 
> 
> Hi,
> 
> it seems your command was `go get github.com/kniren/gota`. This points to an outdated version of gota. Please try `go get github.com/go-gota/gota`.
> For further questions, you can also use our [Slack channel](https://gophers.slack.com/archives/C026APJUHA6).
> 
> Have Fun

I'll test now.

**Comment by jcbritobr** [comment]
Yes, that worked, but I think I read that old version on documentation.

**Comment by chrmang** [comment]
Thank you for your feedback. I'll update the pages.
