### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by Berghuette** [go-gota/gota#170]
go get github.com/kniren/gota/dataframe
leads to
go get: github.com/kniren/gota@v0.10.1 updating to
        github.com/kniren/gota@v0.12.0: parsing go.mod:
        module declares its path as: github.com/go-gota/gota
                but was required as: github.com/kniren/gota
VS-Code shows errors after that.
Can you please fix it?

**Comment by streamdp** [comment]
Hi, @Berghuette 
You sould replace **"github.com/kniren/gota"** in **go.mod** and **main.go** files with **"github.com/go-gota/gota"**.
 The repository is now at this url.

**Comment by chrmang** [comment]
@Berghuette : Where did you find `github.com/kniren/gota/dataframe` ? I think I fixed all old package references.

**Comment by streamdp** [comment]
@chrmang I think he found this for some kind of tutorial on the Internet, they are updated not so often :) I also had it
