### ISSUE TITLE
Support bitwise left-shift and right-shift

### ISSUE THREAD

**Issue by szaydel** [go-gota/gota#49]
I was wondering how you feel about series of Integers supporting bitwise operations like shifts? I actually realized that I could benefit from this in my own work, where for example I have a whole bunch of numbers that are say in kilobytes, but I really want to operate on bytes instead of KBs.

Thanks!

**Comment by kniren** [comment]
This is not currently in the scope of the project, but function application over rows/columns should be able to deal with this use case.
