### ISSUE TITLE
Add Donation Link

### ISSUE THREAD

**Issue by ttelfer** [go-gota/gota#59]
Would it be possible to add a donation link? I would like to buy you a beer/coffee for all your hard work.

**Comment by baram204** [comment]
Yes, he's doing remarkable job.

**Comment by danicat** [comment]
Thanks for your interest in supporting us. We've just recently changed from being a project owned by a single contributor to a collective effort, and while earning money is a nice thing I don't think any of us is working in this particular project with that in mind. Also, this kind of contribution would be more fair if it were made to the original author. 

Anyway, that said, if you still want to contribute to this project, submit your PRs, open your issues and comment about it. Those are the best ways to contribute at the moment :)
