### ISSUE TITLE
Golang + Dataframes + Arrow

### ISSUE THREAD

**Issue by cjnolet** [go-gota/gota#68]
I stumbled upon your repo while searching around to see if anybody is using the Golang hooks for the Apache Arrow library.

I read an article recently from Wes Mckinny about his involvement with Arrow and how he’s stoked to provide a more flexible Pandas API that would support parallelism out of the box with shared memory, rather than the default pickled approach.

I’d love to see this implemented in golang. I can imagine using the Plasma store API that it would be pretty easy.

**Comment by xhochy** [comment]
Arrow nowadays has a native Golang implementation that one could build upon: https://github.com/apache/arrow/tree/master/go/arrow

**Comment by arshpreetsingh** [comment]
Yes I looked for arrow with Pandas as well, which is caled Modin, Can anyone tell how tis can be used with This Pandas Library?

**Comment by kniren** [comment]
I believe https://github.com/tobgu/qframe supports arrow. No support planned for Gota for now.
