### ISSUE TITLE
Support for civil Package (Date, DateTime, civil.Time)

### ISSUE THREAD

**Issue by pjebs** [go-gota/gota#71]
It would be good if a Dataframe can support 
* `civil.Date` (ie. 1955-04-30)
* `civil.DateTime` (this is not the same as `time.Time`)
* `civil.Time`
* `time.Time` (already mentioned in numerous other issues eg https://github.com/kniren/gota/issues/22)

- Also the ability to sort
- Also on loading, specify a column needs to be interpreted using custom parse which produces a type mentioned above.

Ref: https://godoc.org/cloud.google.com/go/civil

**Comment by pjebs** [comment]
https://github.com/rocketlaunchr/dataframe-go library supports generic datatypes.

**Comment by kniren** [comment]
Time support is desired, but I would not want to add any dependencies to external packages. I'm closing this issue in favor of #93 and others.
