### ISSUE TITLE
Support for int64

### ISSUE THREAD

**Issue by pjebs** [go-gota/gota#72]
It would be nice if the type `Int` was internally an `int64`. It would prob be backwards compatible too if the change was made immediately. Obviously it would take up more memory but currently the package doesn't support `time.Time` so I wanted to convert to Unix timestamp, but it can't cleanly support that either without an offset.

**Comment by pjebs** [comment]
https://github.com/rocketlaunchr/dataframe-go

**Comment by kniren** [comment]
Probably we do want other types indeed, like int64 or unsigned types, closing this issue in favour of #22
