### ISSUE TITLE
Support Append data (new row) to a Series and/or DataFrame

### ISSUE THREAD

**Issue by pjebs** [go-gota/gota#73]
I can see that `func (s *Series) Append(values interface{})` can be used to append data to the end of the `Series`.

How can I insert a new row at an arbitrary position?

It would be great to be able to do it for a `DataFrame` too. Not just for a `Series`.

**Comment by pjebs** [comment]
https://github.com/kniren/gota/issues/69#issuecomment-398107918 shows how to append.

**Comment by pjebs** [comment]
https://github.com/rocketlaunchr/dataframe-go

**Comment by mannharleen** [comment]
@pjebs I ve created a PR with the relevant changes that would implement an insert at arbitrary position. Happy for feedback. If in doubt, checkout the tests on usage

**Comment by mannharleen** [comment]
Any specific reason for closing this issue?

**Comment by pjebs** [comment]
I created my own package: https://github.com/rocketlaunchr/dataframe-go
I consider this package to for all intents and purposes unmaintained.
