### ISSUE TITLE
How I can apply multiple values to a Dataframe Filter function. 

### ISSUE THREAD

**Issue by arshpreetsingh** [go-gota/gota#85]
I have following: 
df = df.Rename("Account", "AccountID").
    Filter(dataframe.F{"Event", "==", "bounced"}).
    Filter(dataframe.F{"Event", "==", "Sent"})

I want to do it like as: 

df = df.Rename("Account", "AccountID").
    Filter(dataframe.F{"Event", "==", ["bounced","Sent"]})

Is that possible?

**Comment by danicat** [comment]
Yes, it is, but you need to use the proper comparison functions. Please have a look at the Filtering section in the README: https://github.com/go-gota/gota#filtering

**Comment by arshpreetsingh** [comment]
@danicat Looked into that already, not the one I am looking for,Please have a look a my code.

**Comment by kniren** [comment]
@arshpreetsingh I'm afraid you are not expressing yourself very clearly, but if what you want is an OR comparison (i.e. Event is equal to bounced or Event is equal to Sent), you can put two filters like such:

`df = df.Rename(...).Filter(dataframe.F{"Event", "==", "bounced"}, dataframe.F{"Event", "==", "Sent"})`

Please, next time make sure to read the documentation, as @danicat has pointed out.

**Comment by arshpreetsingh** [comment]
@kniren I had expressed My self, Already know what you and @danicat suggested.  I was asking is it possible to pass multiple values in one Filter, 
```
df = df.Rename(...).Filter(dataframe.F{"Event", "==", "bounced","Sent","Received"}

``` 
Huge thanks for reply.

**Comment by danicat** [comment]
Actually, having a second look at this you can use the "in" comparator.

**Comment by kniren** [comment]
Does this answer your question @arshpreetsingh? If so, we should close the issue.

**Comment by kniren** [comment]
No answers from OP. Closing this issue.
