### ISSUE TITLE
findType panics on empty string

### ISSUE THREAD

**Issue by durp** [go-gota/gota#87]
given: arr = []string{""}
```
func findType(arr []string) series.Type {
	var hasFloats, hasInts, hasBools, hasStrings bool
	for _, str := range arr {
		if str == "" || str == "NaN" {
			continue
		}
```

panics because the loop continues without setting a type...
Is this the intended behavior?
Or should `hasStrings` be set for "" | "NaN" ?
Or is there a missing case?

**Comment by danicat** [comment]
I believe this should be solved by #91. If you please could test with the latest version of the `dev` branch and get back to us it would be very helpful.
