### ISSUE TITLE
ReadCSV unable to handle quotes in non-quoted field / no LazyQuotes option?

### ISSUE THREAD

**Issue by rterryn** [go-gota/gota#95]
Hi, I keep getting the below error, which has a simple solution for go csv package, i.e., set LazyQuotes = TRUE. However, I am not seeing anything similar in LoadOptions for dataframe package. Is a similar option not available to deal with quotes that occur in the middle of a non-quoted field? If not can you suggest proper way to deal with this, as I am very new to GO? 

Code:
	f, err := os.Open("/home/rterryn/go/src/gndwEtl/dataFiles/SGD_features.tab")
	if err != nil {
		// handle this error better than this
		panic(err)
	}
	df := dataframe.ReadCSV(bufio.NewReader(f), dataframe.WithDelimiter('\t'))

Error:
"DataFrame error: parse error on line 265, column 303: bare " in non-quoted-field"

**Comment by karthikcru** [comment]
having the same issue

**Comment by rterryn** [comment]
> having the same issue

Hi. Dataframes uses the standard csv library so I was able to add the lazyQuotes option by modifying dataframes.go with the following, but I do not have this on a public repo anywhere at the moment, sorry:
//create lazy quotes bool variable
lazyQuotes bool

//add new function WithLazyQuotes
func WithLazyQuotes(b bool) LoadOption {
	return func(c *loadOptions) {
		c.lazyQuotes = b
	}
}

//modify the existing ReadCSV function with the lazyQuotes option
func ReadCSV(r io.Reader, options ...LoadOption) DataFrame {
	csvReader := csv.NewReader(r)
	cfg := loadOptions{
		delimiter: ',',
		lazyQuotes: false,
	}
	for _, option := range options {
		option(&cfg)
	}
	if cfg.delimiter != ',' {
		csvReader.Comma = cfg.delimiter
	}

	if cfg.lazyQuotes != false {
		csvReader.LazyQuotes = true
	}
	

	records, err := csvReader.ReadAll()
	if err != nil {
		return DataFrame{Err: err}
	}
	return LoadRecords(records, options...)
}
